name: Compile Ren'Py Scripts

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y wget unzip

    - name: Download Ren'Py SDK
      run: |
        wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
        tar -xjf renpy-8.1.3-sdk.tar.bz2
        mv renpy-8.1.3-sdk renpy-sdk

    - name: Compile .rpy files
      run: |
        ./renpy-sdk/renpy.sh ./ game --compile

    - name: Upload .rpyc files
      uses: actions/upload-artifact@v3
      with:
        name: compiled-rpyc
        path: game/*.rpyc
